name: Build and run docker image
on:
  push:
    branches: ["main"]

jobs:
  docker-push:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: heywaasabi/waasabi-co-md:latest

  docker-run:
    name: Run container
    runs-on: self-hosted
    needs: docker-push
    steps:
      - name: Pull image
        run: docker pull ${{ secrets.DOCKERHUB_IMAGE }}

      - name: Stop and delete previous container
        run: |
          docker stop waasabi_co && \
          docker rm waasabi_co

      - name: Run container image
        run: |
          docker run -d \
            -p 3000:3000 \
            --name waasabi_co \
            ${{ secrets.DOCKERHUB_IMAGE }}
